### ISSUE TITLE
Problem with resource which switching profiles

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#103]
While switching to tabular profile it adds extra empty item into .resource.

**Comment by alexeyk** [comment]
Tabular profile, resource section have ```minItems: 1``` attribute
 https://www.dropbox.com/s/u6erorgryh2g20w/Скриншот%202015-07-17%2009.19.01.png?dl=0
but ```datapackage``` have ```minItems: 0```.
https://www.dropbox.com/s/1u7leomgddzfuej/Скриншот%202015-07-17%2009.19.37.png?dl=0
