### ISSUE TITLE
Auto-fill from ckan fails on firefox

### ISSUE THREAD

**Issue by davidread** [okfn/datapackagist#107]
Using the example link in the README:

http://datapackagist.okfnlabs.org/#/base/from/?url=http%3A%2F%2Fdatahub.io%2Fapi%2Faction%2Fpackage_show%3Fid%3Dpopulation-number-by-governorate-age-group-and-gender-2010-2014

does not fill in the form on firefox. Note error in console.

![field_error](https://cloud.githubusercontent.com/assets/307612/8749307/b04bec70-2c98-11e5-856d-9dd30d783269.png)

However it works on chrome. My colleague on ubuntu gets the same behaviour.

**Comment by pwalsh** [comment]
@gvidon please check this

**Comment by gvidon** [comment]
Probably other browser should be checked too.

**Comment by alexeyk** [comment]
Tested FF, Chrome, Safari. This issue is okay for all.
But Safari have issue in reduce-object lib https://www.dropbox.com/s/po9qsk567k3tlx2/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-20%2006.56.57.png?dl=0 .
