### ISSUE TITLE
On first load (and subsequent), with base profile, get empty resource, and error message on resource name

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#109]
Expected behaviour:

* No empty resource (base profile does not declare one)
* IF we have an empty resource, no error message on name (as we haven't touched the field yet)

<img width="1280" alt="screenshot 2015-07-19 11 58 19" src="https://cloud.githubusercontent.com/assets/791678/8765280/b5d8905a-2e0d-11e5-9a3e-4bc03abb6c62.png">

**Comment by gvidon** [comment]
@pwalsh I thought I fixed it yesterday. Did you try latest changes from repo?

**Comment by pwalsh** [comment]
Yes I also added a commit after your latest: https://github.com/okfn/datapackagist/commits/master
