### ISSUE TITLE
No errors shown when invalid datapackage.json uploaded

### ISSUE THREAD

**Issue by gvidon** [okfn/datapackagist#115]
No errors shown when invalid ```datapackage.json``` uploaded with Upload button, they are currently just ignored — https://github.com/okfn/datapackagist/blob/master/datapackagist/src/scripts/components/ui/upload.js#L21
```javascript
if(!R.valid)
  return false;
```

**Comment by gvidon** [comment]
**How it should work**
* If invalid json uploaded then show modal box with message and single button — "JSON is invalid OK"
* is json is valid then apply it to the form and show errors in typical way — red text under invalid property

**Comment by alexeyk** [comment]
I found issue with detecting changes of form. Probably depended of ```JSONEditorView```. For now it fire initial ```change``` event 3 times, except 2 as previous. Fixed per dedicated commit included in this issue.

**Comment by gvidon** [comment]
- [ ] @alexeyk uploading invalid format json doesn't work

```json
{
  "name": "A"
}
```

https://www.dropbox.com/s/lskjdjhy4rz3i2b/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-24%2015.40.04.png?dl=0
