### ISSUE TITLE
Deploy the node app to Heroku

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#124]
Until recently, we ran DataPackagist as a pure client-side application, and served from GitHub Pages. 

In order to ease functional testing and provide other routing functionality that requires a proper server, we ported the code into an Express.js app running on `iojs`. 

We now need to deploy this app to Heroku so we can direct users from the static, gh-pages app to the iojs-based one.

Access has been granted to `datapackagist` on Heroku. Default URL is `datapackagist.herokuapp.com`.

## Tasks

* [x] Add appropriate files for Heroku, eg `Procfile`
* [x] Check deployment works, etc. Especially the whole thing with building the static resources post install

**Comment by gvidon** [comment]
@pwalsh no need in ```Procfile```, was able to maintain deployment by just scripts section of ```package.json```:
* https://devcenter.heroku.com/articles/deploying-nodejs#specifying-a-start-script
* https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process

But it required to move gulp dependencies from ```devDependencies``` into ```dependencies```, increasing ```app.min.js``` file size.

**Comment by pwalsh** [comment]
Why does `app.min.js` need to increase in size?

**Comment by gvidon** [comment]
App deployed and running — http://datapackagist.herokuapp.com/ Should I close the task or wait for #126?
