### ISSUE TITLE
Fix Travis test runner

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#125]
Seems to be broken: https://travis-ci.org/okfn/datapackagist

**Comment by gvidon** [comment]
@pwalsh did you mean travisci test runner and not heroku?

**Comment by pwalsh** [comment]
yes

**Comment by gvidon** [comment]
Done https://travis-ci.org/okfn/datapackagist/builds/76598074

**Comment by pwalsh** [comment]
great!
