### ISSUE TITLE
Fix bundles and dependencies in package.json

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#126]
* [x] Ensure nothing is in package.json that is no longer a direct dependency
  * eg: https://github.com/pwalsh/datapackagist/blob/master/package.json#L36
* [x] Ensure that all dependencies are in the [vendored dependencies array](https://github.com/okfn/datapackagist/blob/master/gulpfile.js#L22), so they are included in `vendor.min` and not `app.min`

**Comment by gvidon** [comment]
**Possible solution**
* Grab list of production dependencies from ```package.json``` and build vendor bundle based on it
* build ```ignore``` array of app bundle on the same list of dependencies.

**Comment by pwalsh** [comment]
`app.min` already ignores: https://github.com/okfn/datapackagist/blob/master/gulpfile.js#L45

All that you need to do is update the array, for the `app.min` `vendor.min` thing.
