### ISSUE TITLE
Fix npm warning related to handlebars

### ISSUE THREAD

**Issue by gvidon** [okfn/datapackagist#129]
Need to fix npm warn message thrown during ```npm i```
![2015-08-24 12 03 09](https://cloud.githubusercontent.com/assets/58164/9436488/658f55ea-4a58-11e5-8d4b-1a7ae982d58f.png)

**Comment by alexeyk** [comment]
@gvidon i have different warnings:
![screenshot]
(https://www.dropbox.com/s/753685yq8fd9675/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-08-26%2000.28.46.png?dl=0)
should i fix these?

**Comment by alexeyk** [comment]
i reinstalled ```node_modules``` folder and clear any error messages on ```npm i```
https://goo.gl/57CI38

**Comment by gvidon** [comment]
Ok, will take a look and write detailed scenario on how to reproduce if it is still exist.
