### ISSUE TITLE
Show error message when trying to upload and parse malformed CSV

### ISSUE THREAD

**Issue by gvidon** [okfn/datapackagist#130]
I tried to upload resource datafile which actually was html file with ```.csv``` extension. Didn't see any error message except one in dev console:

![2015-08-24 12 18 28](https://cloud.githubusercontent.com/assets/58164/9436756/46ad2d26-4a5a-11e5-885d-72fcfa657b3e.png)

![2015-08-24 12 19 11](https://cloud.githubusercontent.com/assets/58164/9436770/5ce5ff50-4a5a-11e5-873d-191c85c68eec.png)

Looks like parsing errors are thrown silently for regular user and this may lead to bad UX.

## Task
If user is trying to upload malformed ```.csv``` show modal box with thrown error and tell user that it possible means bad/wrong file content.

**Comment by alexeyk** [comment]
@gvidon i'm sorry, fixed direct in master.

**Comment by pwalsh** [comment]
@alexeyk @gvidon this **must** have a passing test added for it.

**Comment by gvidon** [comment]
@pwalsh you are right, I forgot to mention it. @alexeyk I will add empty test case with description today.

**Comment by gvidon** [comment]
@alexeyk it should be written in different branch.

**Comment by gvidon** [comment]
@alexeyk please add this in your branch and implement
```javascript
it('shows modal error message when uploading malformed/broken csv as resource', function(done) {})
```
