### ISSUE TITLE
Should 'Name' and 'Title' fields be swapped?

### ISSUE THREAD

**Issue by danfowler** [okfn/datapackagist#132]
I understand that the 'name' field is required so it makes sense to be at the top, but the way this functionality tends to work on other sites is the user fills in the human-readable field (e.g. 'title') and the website generates the machine-readable field (e.g. 'name') by 'slugifying' the human-readable field according to the rules (e.g. lower-casing and so on).

**Comment by gvidon** [comment]
I would agree. From my experience most typical UX is to create machine name from human readable. Probably we should swap title and name behaviors in their relation.

**Comment by pwalsh** [comment]
In general, I agree, but I don't want to make this change now, due to the way the spec works in regard to this.

**Comment by pwalsh** [comment]
I'm closing this. I think this is the right way to do it considering the field requirements for data packages.
