### ISSUE TITLE
Heroku app wakes up too long

### ISSUE THREAD

**Issue by gvidon** [okfn/datapackagist#133]
After an hour of no http requests heroku dyno will sleep https://blog.heroku.com/archives/2013/6/20/app_sleeping_on_heroku. It means that dyno container which hosts built app will be completely erased with all its files https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

After that, once heroku app which *sleeps* receives request it starts building new container from scratch (like if someone runs ```npm run deploy```) — build all js/css bundles. It takes too long. So, some users may feel like app is broken,while it is actually in build stage.

If even it is a problem, possible solutions would be
* paid dynos never sleep
* use cdn for deploying app bundles.

**Comment by pwalsh** [comment]
fine for now. will move to paid dyno in future.
