### ISSUE TITLE
Show error message when uploading malformed datapackage.json

### ISSUE THREAD

**Issue by gvidon** [okfn/datapackagist#139]
Presently if user uploads any ```.json``` which is not valid ```datapackage.json``` nothing happen. Need to show modal box with error message just like in https://github.com/okfn/datapackagist/issues/130

**Comment by pwalsh** [comment]
Similar to https://github.com/okfn/datapackagist/issues/130

Please ensure we have passing tests for this once implemented.

**Comment by gvidon** [comment]
@alexeyk please write these tests with mocks — no remote http requests at all.
