### ISSUE TITLE
Is there a term for describing a set of schemas?

### ISSUE THREAD

**Issue by whyvez** [okfn/datapackagist#145]
In the case where you have a set of schemas which together for a "type" of dataset. Is there a term or standard to describe what that "type" is? Initially we where calling them data themes. We then found a data profile but now I'm thinking its a not the same. A profile seems like a higher level standard.

Is there a term/standard for defining one or many resource schemas for a specific application?

**Comment by pwalsh** [comment]
Hi @whyvez 

The place where we discuss all the spec-related issues around Data Package and JSON Table Schema is the [Data Protocols Issue Tracker](https://github.com/dataprotocols/dataprotocols/issues).

I'm not exactly sure what you are looking for here. Can you provide some example data to help illustrate the problem you are trying to solve?

**Comment by whyvez** [comment]
@pwalsh Yes for sure. Here is an example.

https://github.com/tesera/datatheme-pgyi

This is what we've been referring to as a "data theme". (collection of schemas which compose a dataset)

There are a few issues (pkey & fkey not in schema) with the current implementation which I'm working on cleaning up now.

A data theme could be managed like this repo where the schema can be versioned or can also be more ad-hoc. Does this exist? Does it make sense?  Should it just be called "dataset schema"?

Thoughts?

Can move this discussion into the dataprotocol repo if you think it makes sense.

**Comment by whyvez** [comment]
@pwalsh here is my cleanup branch: https://github.com/tesera/datatheme-pgyi/tree/cleanup

**Comment by whyvez** [comment]
renamed the repo: https://github.com/tesera/datatheme-afgo-pgyi

**Comment by pwalsh** [comment]
@whyvez Sorry for the hassle, but would you mind opening this up on https://github.com/dataprotocols/dataprotocols/issues

The benefit is that many more eyes are there and we'll be able to address your issue. When you do create there, pls let me know and I'll close this issue and point to there.

**Comment by whyvez** [comment]
@pwalsh My apologies. https://github.com/dataprotocols/dataprotocols/issues/219

**Comment by pwalsh** [comment]
@whyvez totally fine.
