### ISSUE TITLE
Local Development issue (XMLHttpRequest cannot load https://rawgit.com/dataprotocols/registry/master/registry.csv)

### ISSUE THREAD

**Issue by richhall** [okfn/datapackagist#146]
I have followed the instructions under Local Development.
My environment is:

Windows 8.1
Chrome Version 45.0.2454.101 m
Internet Explorer 11.0.9600.17937

I have installed Visual Studio Express 2013 as a version of Visual Studio is required to build some of the dependencies.

This works okay.  When I launch locally the "Select Profile" dropdown is blank and Chrome flags the following cross site scripting issue:

XMLHttpRequest cannot load https://rawgit.com/dataprotocols/registry/master/registry.csv. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:3000' is therefore not allowed access.

The problem persists even if running Chrome with --disable-web-security flag

**Comment by pwalsh** [comment]
@gvidon please check what this is, and fix, or, explain steps to mitigate.

**Comment by gvidon** [comment]
@richhall could you please share all the headers you see in broken request?

**Comment by richhall** [comment]
![image](https://cloud.githubusercontent.com/assets/1749835/10267656/3525ab28-6a94-11e5-8808-df44db630502.png)

Request URL:https://rawgit.com/dataprotocols/registry/master/registry.csv
Request Method:GET
Status Code:200 OK

**Response Headers**
access-control-allow-origin:*
cache-control:max-age=300
content-encoding:gzip
content-type:text/csv;charset=utf-8
date:Sun, 04 Oct 2015 11:31:38 GMT
etag:W/"f5441c89ffafdd384158a9cc16e4554f3bb3537a"
rawgit-cache-status:HIT
rawgit-naughtiness:0
server:nginx
status:200 OK
vary:Accept-Encoding
version:HTTP/1.1
x-content-type-options:nosniff
x-robots-tag:none

**Request Headers**
:host:rawgit.com
:method:GET
:path:/dataprotocols/registry/master/registry.csv
:scheme:https
:version:HTTP/1.1
accept:*/*
accept-encoding:gzip, deflate, sdch
accept-language:en-US,en;q=0.8
cache-control:no-cache
origin:http://localhost:3000
pragma:no-cache
referer:http://localhost:3000/
user-agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
	
35 requests ❘ 2.4 MB transferred ❘ Finish: 1.60 s ❘ DOMContentLoaded: 1.42 s ❘ Load: 1.56 s

**Console**
vendor.min.js:11 Refused to set unsafe header "accept-encoding"
vendor.min.js:11 Refused to set unsafe header "user-agent"
(index):1 XMLHttpRequest cannot load https://rawgit.com/dataprotocols/registry/master/registry.csv. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:3000' is therefore not allowed access.
vendor.min.js:22 Uncaught TypeError: Cannot read property 'content-type' of undefined
app.min.js:18 Uncaught TypeError: Cannot read property 'text' of undefined

**Comment by gvidon** [comment]
@richhall please try now. I have recently deployed the branch with CORS proxy feature. Don't see any errors in IE11.

**Comment by richhall** [comment]
@gvidon Great job - this is working for me now in Chrome and IE11.
