### ISSUE TITLE
Internet Explorer issue (integrations)

### ISSUE THREAD

**Issue by richhall** [okfn/datapackagist#147]
Internet Explorer issue (integrations)

The following example in IE11:
http://datapackagist.okfnlabs.org/base/from/?url=http%3A%2F%2Fdatahub.io%2Fapi%2Faction%2Fpackage_show%3Fid%3Dpopulation-number-by-governorate-age-group-and-gender-2010-2014

gives SCRIPTS: Access is denied.
File: okf-panel.html, Line 1, Column 1
![image](https://cloud.githubusercontent.com/assets/1749835/10122265/0b9111b4-650b-11e5-857a-7d31a36f98d4.png)

The package data on the left populates but the JSON on the right is empty:
![image](https://cloud.githubusercontent.com/assets/1749835/10122262/e947b4e6-650a-11e5-8a8b-653f6c213b6f.png)

My environment is:
Windows 8.1
Internet Explorer 11.0.9600.17937

I think this issue relates to IE's policies around cross site scripting.  Having this functionality working smoothly in IE is an important use case for UK public sector adoption of the tool.

**Comment by pwalsh** [comment]
@gvidon we would like to get down even to IE9 support if possible. Can you please address this and let us know. Definitely, I'd expect IE10 and 11 to work pretty much as part of the core code functionality, and maybe IE9 with some additional, targeted polyfills, etc.

**Comment by pwalsh** [comment]
@gvidon any progress here?

**Comment by gvidon** [comment]
@pwalsh not yet, I had problems with launching IE9 in VM locally and switched to other tasks.

**Comment by pwalsh** [comment]
#180
