### ISSUE TITLE
Clarification (API endpoint security)

### ISSUE THREAD

**Issue by richhall** [okfn/datapackagist#148]
In Chrome this integration example with a CKAN endpoint:
http://datapackagist.okfnlabs.org/base/from/?url=http%3A%2F%2Fdatahub.io%2Fapi%2Faction%2Fpackage_show%3Fid%3Dpopulation-number-by-governorate-age-group-and-gender-2010-2014
works as expected whereas this example using a DKAN endpoint:
http://datapackagist.okfnlabs.org/base/from/?url=http%3A%2F%2Fopendata.cambridgeshireinsight.org.uk%2Fapi%2F3%2Faction%2Fpackage_show%3Fid%3D965509fe-fedc-474c-aa00-3c647721de31
does nothing.
Chrome console gives:
Error while process. End point request failed: Error: Origin is not allowed by Access-Control-Allow-Origin
![image](https://cloud.githubusercontent.com/assets/1749835/10122337/f9f69890-650d-11e5-995d-2a24fbbfdc36.png)
Looking at the response headers the datahub.io endpoint includes the following headers that are not returned from the opendata.cambridgeshireinsight.org.uk endpoint:
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, PUT, GET, DELETE, OPTIONS
Access-Control-Allow-Headers: X-CKAN-API-KEY, Authorization, Content-Type
![image](https://cloud.githubusercontent.com/assets/1749835/10122342/2a78e194-650e-11e5-961a-143c5fe6b8ef.png)

It would be worth confirming the required response headers for any endpoint to work with the tool.

From a user experience perspective at first glance it looks like the packagist tool doesn't work.  Is there an easy way to catch this issue and display it in a user friendly manner, perhaps with a link to help portal owners resolve potential endpoint issues with their respective technology providers?

**Comment by gvidon** [comment]
If security is not a paranoid option I would suggest using CORS proxy to avoid the problem described above. The only other option would be implementing own backend for downloading remote resources.

**Comment by pwalsh** [comment]
@gvidon isn't this issue just a problem with the server we get data from (the DKAN instance in this case noted by @richhall). Obviously, if a server does not allow cross origin requests, there is not much DataPackagist can do about it (or, is there another issue here?).

**Comment by gvidon** [comment]
@pwalsh yes, exactly, if there is no appropriate ```allow-origin``` header we can't get resource without special tool. The problem is that valuable part of resources will **not** have this header, and this will confuse UX as we will have to tell users technical details about why we can't upload resource.

I suggest using cors proxy or local backend to completely forget about CORS problem.

**Comment by pwalsh** [comment]
@gvidon I think we'll move to a local backend then, seeing as we have this running out of a node server now anyway. Would we be able to run the new tabular file manager code you wrote on the backend for this?

**Comment by gvidon** [comment]
@pwalsh no, file manager is designed to work with resources (parse and infer schema of CSVs), not data packages json. Or did I misunderstand your point?

**Comment by richhall** [comment]
@pwalsh @gvidon Thanks for your efforts so far - we're making good progress I think.  Following on from conversation here: https://github.com/okfn/datapackagist/pull/162 I've requested that we align http://opendata.cambridgeshireinsight.org.uk with http://demo.getdkan.com and add the 
```
Access-Control-Allow-Origin: *
```
header.  Until this is in place, my local build currently now errors at the point it tries to retrieve the CSV file:
![image](https://cloud.githubusercontent.com/assets/1749835/10371472/76ae2be8-6ddb-11e5-94db-c265e9a4794e.png)

```
XMLHttpRequest cannot load http://opendata.cambridgeshireinsight.org.uk/files/ci_opendata/2014%20Retail%20and%20Town%20Centre_0.csv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Uncaught TypeError: Cannot read property 'text' of undefined(anonymous function) @ vendor.min.js:37p.callback @ vendor.min.js:36p.crossDomainError @ vendor.min.js:36p.end.n.onreadystatechange @ vendor.min.js:36
```

(datapackage: https://rawgit.com/richhall/4f2b94ae058317f6ac39/raw/7fbbd5965410898e0562103c1481e72a1b52765f/opendata_cambridgeshireinsight_org_uk_example.json)

I am thinking it would be good to provide a warning but have the ability to work around it (using CORS proxy or server-side fix) as previously mentioned.  That way we give some useful information back for portal owners (that they could send to their IT provider) but without "breaking" the tool from the end user perspective.  There may be some scenarios where someone wants to create a datapackage.json for csv files that are hosted on a more general web site.  For example a .gov.uk web site where they either:
* may not have granular control over the security headers.
* may consider blanket access control a risk (e.g. if the same site hosts online transactions)

To produce frictionless open data we need frictionless open data tools!

What do you think?

**Comment by gvidon** [comment]
@richhall thank you for such detailed feedback. Which exactly scenario do you mean?
* Try to download resource without CORS proxy. Show error message if it is not possible and retry with CORS proxy enabled.
* Or. Try to download resource without CORS proxy. Show error message if it is not possible and ask user if we should retry with CORS proxy enabled.

Regarding to errors — do you try app in branch ```hotfix/proxy-cors```?

**Comment by richhall** [comment]
@gvidon:

Possibly this one:
* Try to download resource without CORS proxy. Show error message if it is not possible and retry with CORS proxy enabled.

so the user experience is similar to the "your browser is out of date" banners.  Interested to hear @pwalsh's view on this. 

I'm getting the same error using the hotfix/proxy-cors branch (I think I retrieved and built it correctly).  Resource CSVs aren't coming via the proxy for me.  I've created a gist datapackage which explicitly proxies the CSVs so that we can progress with testing the CSV parsing.

**Comment by gvidon** [comment]
Implementing backend for proxying CORS.

**Comment by pwalsh** [comment]
@gvidon not for proxying: actually for upload and handling of files, and then providing them to ui.

**Comment by gvidon** [comment]
@pwalsh at the moment I didn't expect to do nothing more than
* get URL from client side
* request this URL and get text data
* send retrieved text data back to the client.

Did I miss something?

**Comment by pwalsh** [comment]
yes: for example the work for partially reading files, etc, as we did on os-import. If we can partially read a file (sample) on server, no need to send it all back to client. 

Can't we use the work you did on file manager for os-import (in some way)?

**Comment by gvidon** [comment]
```tabularfilemanager``` is only suitable for CSVs (or other data formats, in the future) by its nature https://github.com/openspending/os-import/blob/hotfix/components-decoupling/os-import/src/scripts/components/tabularfilemanager/from-url.js It's ```maxSize``` only works with CSV.

But we also need to download JSON data. So,
* we can go with generic and the simplest solution on backend — just proxy everything requested and do other processing on client side
* or we can have two backend routes. One for CSV (with file size reduction) and another one for JSON.

**Comment by pwalsh** [comment]
@gvidon I'll write a spec first, ok?

**Comment by gvidon** [comment]
Ok, I can proceed to other tasks. By the moment generic solution is ready, I will push it to some branch.

**Comment by pwalsh** [comment]
what do you mean generic solution is ready?

**Comment by gvidon** [comment]
I mean this on
> we can go with generic and the simplest solution on backend — just proxy everything requested and do other processing on client side

**Comment by pwalsh** [comment]
@gvidon ok, let's merge that in as a first step.

**Comment by gvidon** [comment]
@pwalsh updated this PR https://github.com/okfn/datapackagist/pull/162, please take a look.
