### ISSUE TITLE
Add datapackage.json or resource from local or URL

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#149]
Currently when the user makes an Upload action (for a datapackage) or "Upload data file" action to add a resource, the user can only upload from local machine. We want to allow either local machine or remote URL.

For each the upload data package.json action, and the upload data file action:

* [x] Clicking the action pops a small in context div with two actions: "Upload" or "Via URL"
* [x] Depending on the user choice, either add a new inout to add a URL, or use the file upload interface of the browser

First focus on the implementation of this, we'll tidy up the design of the dialog after we see the implementation.

**Comment by gvidon** [comment]
@pwalsh do we really need start it before local backend for proxying requests is ready? I mean this https://github.com/okfn/datapackagist/issues/148#issuecomment-145466921
