### ISSUE TITLE
Problems with from-remote not working on some browsers

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#156]
Using examples from README:

* Does not work in Firefox 39, 
* Does not work in IE9

**Comment by gvidon** [comment]
@pwalsh probably this PR https://github.com/okfn/datapackagist/pull/162 should fix the problem at least in fx 39 (on Mac OSx). I pushed it to the heroku. Tried all examples listed in README.

**Comment by pwalsh** [comment]
@gvidon need to be certain, not probably :). I'm closing this but it should be verified when doing https://github.com/okfn/datapackagist/issues/171
