### ISSUE TITLE
Clarification (Version parameter)

### ISSUE THREAD

**Issue by richhall** [okfn/datapackagist#164]
Hi,

The readme states:
"version: The version of the API of the source type. defaults to 3.0, which is the current CKAN version."

Are any other versions supported?
http://data.gov.uk runs on CKAN and looks like it supports version 2 of the api:

**Example:**
Dataset: https://data.gov.uk/dataset/retail-and-town-centre-2014_1/
Endpoint: https://data.gov.uk/api/2/rest/package/retail-and-town-centre-2014_1

Can you confirm what is implemented/supported?

**Context:**
@pwalsh I'm noticing inconsistencies in the API JSON between datahub.io, gov.uk and opendata.cambridgeshireInsight.org.uk (DKAN).  I'll put together some gists to illustrate this.  I suspect some things will need to be amended in DKAN.

**Comment by pwalsh** [comment]
@richhall sure. We'll definitely support DKAN. It is just that the DKAN docs state it is consistent with the CKAN API, so I didn't loo for differences. If you can outline them that would be great.

**Comment by pwalsh** [comment]
@richhall we'll support DKAN explicitly in the `data package-from-remote` package, as per #165.

**Comment by pwalsh** [comment]
Will be resolved in https://github.com/okfn/datapackage-from-remote-js/issues/11
