### ISSUE TITLE
DKAN example returns blank data package

### ISSUE THREAD

**Issue by richhall** [okfn/datapackagist#165]
The CORS proxy solution (#162) seems to work nicely to allow opendata.cambridgeshire.org.uk datasets to be used with the packagist.  However, they are still returning blank {} datapackages with no obvious errors in the Chrome console.  This might be due to discrepancies between DKAN and CKAN package_show APIs.  To test I have created some gists to make the package_show JSON more readable.  

**datahub.io example**

Description|URL
-------------|----------------
ORIGINAL|http://datahub.io/api/action/package_show?id=population-number-by-governorate-age-group-and-gender-2010-2014
GIST| https://gist.github.com/richhall/f341bbd37ffedf65cb76
RAW| https://rawgit.com/richhall/f341bbd37ffedf65cb76/raw/49fb4b3844a79ae5ecc318c1203a3c1324814e97/data_hub_io_example.json
PACKAGIST| http://datapackagist.okfnlabs.org/base/from/?url=https%3A%2F%2Frawgit.com%2Frichhall%2Ff341bbd37ffedf65cb76%2Fraw%2F49fb4b3844a79ae5ecc318c1203a3c1324814e97%2Fdata_hub_io_example.json

**Cambridgeshire Insight (DKAN) example**

Description|URL
-------------|----------------
ORIGINAL| http://opendata.cambridgeshireinsight.org.uk/api/3/action/package_show?id=965509fe-fedc-474c-aa00-3c647721de31
GIST| https://gist.github.com/richhall/4f2b94ae058317f6ac39
RAW| https://rawgit.com/richhall/4f2b94ae058317f6ac39/raw/7fbbd5965410898e0562103c1481e72a1b52765f/opendata_cambridgeshireinsight_org_uk_example.json
PACKAGIST| http://datapackagist.okfnlabs.org/base/from/?url=https%3A%2F%2Frawgit.com%2Frichhall%2F4f2b94ae058317f6ac39%2Fraw%2F7fbbd5965410898e0562103c1481e72a1b52765f%2Fopendata_cambridgeshireinsight_org_uk_example.json

Why does the Cambridgeshire Insight example still produces a blank {} datapackage?

**Some notable differences:**
Discrepancy between datahub.io "notes" and opendata.cambridgeshire,gov.uk "description" fields
opendata.cambridgeshire,gov.uk "description" contains html tags
opendata.cambridgeshire,gov.uk forward slashes in uris are escaped

**Same Cambridgeshire Insight example from data.gov.uk (CKAN)**
The same dataset is havested by data.gov.uk so I have also provided gists for that.  However, this still gives a blank {} result with console error 

```
Uncaught TypeError: Cannot read property 'base' of undefined
```

which could be due to version support (see #164) and/or loss of data through the harvesting process:

Description|URL
-------------|----------------
ORIGINAL| https://data.gov.uk/api/2/rest/package/retail-and-town-centre-2014_1
GIST| https://gist.github.com/richhall/452ce3e7374e4bf39acc
RAW| https://rawgit.com/richhall/452ce3e7374e4bf39acc/raw/05986e4a5c1866ac26a0c6c8ef05bce4bf427776/data_gov_uk_example.json
PACKAGIST| http://datapackagist.okfnlabs.org/base/from/?url=https%3A%2F%2Frawgit.com%2Frichhall%2F452ce3e7374e4bf39acc%2Fraw%2F05986e4a5c1866ac26a0c6c8ef05bce4bf427776%2Fdata_gov_uk_example.json&version=2.0

**Comment by richhall** [comment]
**Vanilla DKAN example http://demo.getdkan.com/dataset/afghanistan-election-districts also yields blank {}**

Description|URL
--------------|-----------
ORIGINAL| http://demo.getdkan.com/api/3/action/package_show?id=f870ec17-1839-44c0-9979-86a42cd2452b
GIST| https://gist.github.com/richhall/2377f5512cf9f77cc5fe
RAW|https://rawgit.com/richhall/2377f5512cf9f77cc5fe/raw/60c432cab49dd49d2361ad8304b17e2aec51e99d/dkan_example.json
PACKAGIST| http://datapackagist.okfnlabs.org/base/from/?url=https%3A%2F%2Frawgit.com%2Frichhall%2F2377f5512cf9f77cc5fe%2Fraw%2F60c432cab49dd49d2361ad8304b17e2aec51e99d%2Fdkan_example.json

**Comment by richhall** [comment]
DKAN wraps the package_show result hash in an array. I.e.

CKAN:
```javascript
"result": { 
     ...
    }
```

DKAN
```javascript
"result": [
    { 
     ...
    }
 ]
```

When I amend the previous example gist to take out the array then it works:

Description|URL
--------------|----
GIST| https://gist.github.com/richhall/7a87dc923286a2903e0e
RAW| https://rawgit.com/richhall/7a87dc923286a2903e0e/raw/cd4a5c4c0951c15411e89e157ee79122b50a0e14/dkan_amended_example.json
PACKAGIST| http://datapackagist.okfnlabs.org/base/from/?url=https%3A%2F%2Frawgit.com%2Frichhall%2F7a87dc923286a2903e0e%2Fraw%2Fcd4a5c4c0951c15411e89e157ee79122b50a0e14%2Fdkan_amended_example.json

This issue is noted in DKAN:
https://github.com/NuCivic/dkan/issues/410
https://github.com/NuCivic/dkan/issues/195

I can ask @Forester1 and @tiger-damon if this module:https://github.com/NuCivic/open_data_schema_map#multi-value-fields is available to us in http://opendata.cambridgeshireInsight.org.uk to work around the issue.

@pwalsh in the meantime if it is straightforward then it might be worth differentiating between DKAN and CKAN sources in the datapackagist as long as this issue remains in the core DKAN package_show output.  What do you think?

**Comment by pwalsh** [comment]
@gvidon can you please investigate these examples, and add a new DKAN remote to `datapackage-from-remote`. DKAN and CKAN should be distinct remotes for that package, going forward.

**Comment by gvidon** [comment]
@pwalsh yes, working with it right now.

**Comment by gvidon** [comment]
This PR https://github.com/okfn/datapackage-from-remote-js/pull/9 when published on npm should solve the problem. But it is required to explicitly specify source type in request URL ```&source=dkan``` — http://datapackagist.okfnlabs.org/base/from/?url=https%3A%2F%2Frawgit.com%2Frichhall%2F4f2b94ae058317f6ac39%2Fraw%2F7fbbd5965410898e0562103c1481e72a1b52765f%2Fopendata_cambridgeshireinsight_org_uk_example.json&source=dkan

**Comment by pwalsh** [comment]
okfn/datapackage-from-remote-js#9 merged

**Comment by pwalsh** [comment]
Will be properly resolved here: https://github.com/okfn/datapackage-from-remote-js/issues/11
