### ISSUE TITLE
Lag in processing CSV (managing User Experience)

### ISSUE THREAD

**Issue by richhall** [okfn/datapackagist#167]
Hi,

I have created this example:
http://datapackagist.okfnlabs.org/base/from/?url=https%3A%2F%2Frawgit.com%2Frichhall%2Fa3e534c7f63911c22082%2Fraw%2Fc758f90a07804ffe23ca2f97b8fe696f71106d7f%2Fopendata_cambridgeshireinsight_org_uk_CORS.json

which works around #165 and #148 and loads a CSV resource from http://opendata.cambridgeshireinsight.org.uk.

I think the first issue to discuss is the time it takes to process and the UX during that waiting time:
![image](https://cloud.githubusercontent.com/assets/1749835/10393934/b6e03f7a-6e8b-11e5-9919-452a56192054.png)

....wait 15 seconds or so...

![image](https://cloud.githubusercontent.com/assets/1749835/10393960/d9dc9988-6e8b-11e5-8f7f-58b8c76bb173.png)

It's great that it eventually works but the user experience of it appearing to not work, then potentially hanging in a long running script and then working would confuse our general user base (many of whom don't have a lot of confidence in the browsers that their IT depts force upon them to begin with..)

So - if it is going to take more than a couple of seconds to process the CSV then:

1. we'll need to tell the user that is what is happening and have some indication of process.  
2. it would be worth considering doing this server-side where it is perhaps easier to guarantee performance

@pwalsh what do you think?

**Comment by gvidon** [comment]
@richhall @pwalsh I had a solution for this before — processing just part of CSV and show *Loading...* screen while in loading state. Will check if it is in working condition or something is broken.

**Comment by pwalsh** [comment]
@gvidon is the loader working? Can you also write a test for it.

**Comment by gvidon** [comment]
@pwalsh sorry, haven't yet checked it, was quite busy this weekend. Will check it today and add test cases.

**Comment by pwalsh** [comment]
This is directly addressed in #171 and #173
