### ISSUE TITLE
How is the packagist guessing CSV column type?

### ISSUE THREAD

**Issue by richhall** [okfn/datapackagist#169]
On this example:
http://datapackagist.okfnlabs.org/base/from/?url=https%3A%2F%2Frawgit.com%2Frichhall%2Fa3e534c7f63911c22082%2Fraw%2Fc758f90a07804ffe23ca2f97b8fe696f71106d7f%2Fopendata_cambridgeshireinsight_org_uk_CORS.json

the packagist is incorrectly guessing boolean and geojson types for some of the columns.  @gvidon where in the codebase is this logic and how many rows of data does it look at?

**Comment by pwalsh** [comment]
Hi @richhall the jets code for that is here:

https://github.com/okfn/jsontableschema-js/blob/master/types.js#L452

BTW, you should direct questions to me, and I'll then sync on work with @gvidon and others - it just makes it easier to manage the project. I was away at a summit all last week, and I'm now going over all the current work and scheduling further.

**Comment by richhall** [comment]
@pwalsh okay will do - thanks.

**Comment by borysyuk** [comment]
@pwalsh "guessing" should work much better with refactored library

**Comment by pwalsh** [comment]
@borysyuk great. I pushed your changes to npm as `json-table-schema@0.1.0`. Please integrate here, deploy, and then LMK and we'll close this issue.

**Comment by pwalsh** [comment]
FIXED.
