### ISSUE TITLE
Resource title row not updated after upload

### ISSUE THREAD

**Issue by gvidon** [okfn/datapackagist#175]
After resource uploaded with modal box (from local drive or from remote URL) its title (if it is not empty) is not auto populated from name.

The problem is that there at resource title are no DOM attributes js code uses in its queries.

![2015-10-14 17 14 19](https://cloud.githubusercontent.com/assets/58164/10486311/15a071d8-7297-11e5-9cb1-f2e1b6e5e682.png)

![2015-10-14 17 15 26](https://cloud.githubusercontent.com/assets/58164/10486336/2dbd9732-7297-11e5-87b4-bb70eb44118c.png)

**Comment by pwalsh** [comment]
#179
