### ISSUE TITLE
Calculating resource hash and bytes

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#189]
Is not trivial. We can do it but seems reasonable to leave in backlog now.

**Comment by Stephen-Gates** [comment]
As a data publisher to a shared CKAN portal, I am not aware of the hash algorithm used on my portal. The default algorithm in DataPackagist is MD5. When adding a Hash from my portal, it was rejected as invalid. In reading the [Data Packages standard](http://dataprotocols.org/data-packages/index.html#optional-fields-1) it provides an example of 
`"hash": "sha1:8843d7f92416211de9ebb963ff4ce28125932878"`

So I tried `sha1:` in front of my hash and it worked.

How do I find the hash algorithm for my portal or can a list of valid algorithm options be provided to select from?

**Comment by pwalsh** [comment]
@Stephen-Gates good feedback, thanks. Hashing algorithm is too complex for this user interface, so my preference would be to remove it actually, as it is not a required field.

**Comment by pwalsh** [comment]
I've hidden these fields from the UI. They are too technical for the users we are targeting for the UI.
