### ISSUE TITLE
License label should be Title

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/datapackagist#196]
Firstly, this looks like an interesting project and I am happy to help with testing when you're ready.

There are two "License" labels in the user interface that look like should be labelled "Title" based on the generated JSON file.

<img width="951" alt="licenselabelerror" src="https://cloud.githubusercontent.com/assets/9379524/12141821/b4992898-b4be-11e5-8ebd-533cd2aa29b6.png">

In creating a data package for the data at https://data.qld.gov.au/dataset/test-csc/resource/81d78d4f-0cad-4145-9fe6-43526036cabf I noted a number of other errors: 

 - first column _id not recognised
 - Address 1 incorrectly identified as geojson
 - Latitude incorrectly identified as integer
 - and many more

I also expected to see the Description and Keywords to be displayed before the Resource fields.

Let me know if you want these added as separate issues now or if it's too early in the project for this.

**Comment by pwalsh** [comment]
@Stephen-Gates this is great! We are excited about this project too! 

We consider it almost ready now, but as we've done some heavy refactoring recently, any user feedback like this is perfect. I'd encourage you to do further testing with other datasets if you have the time/desire, and open distant bugs per issue.

@borysyuk please look at this

**Comment by pwalsh** [comment]
@Stephen-Gates specifically about the order of fields, please remove that from here and open as a separate issue.

**Comment by pwalsh** [comment]
# Tasks

* [ ] Fix bug
* [ ] Test coverage for the form label ids / the issue we see here

**Comment by Stephen-Gates** [comment]
@pwalsh done! See #197

**Comment by borysyuk** [comment]
@pwalsh We have 2 copy-paste errors in each files: http://schemas.datapackages.org/data-package.json and 
http://schemas.datapackages.org/tabular-data-package.json

    "title": {
      "$ref": "definitions.json#/define/license",
      "propertyOrder": 20
    }
it should be :

    "title": {
      "$ref": "definitions.json#/define/title",
      "propertyOrder": 20
    }

**Comment by borysyuk** [comment]
@pwalsh i have fized these files in https://github.com/dataprotocols/schemas

**Comment by pwalsh** [comment]
@Stephen-Gates can you confirm that the issue is resolved?

**Comment by Stephen-Gates** [comment]
@pwalsh issue resolved but found another possibly related. Will post separately.
