### ISSUE TITLE
Order of Description and Keywords in user interface 

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/datapackagist#197]
Consider moving the Description and Keywords to be displayed before the Resource fields.

The Description is placed at the top of the json file and so should be at the top of the user interface. It is currently at the very bottom of the form.

I'm less sure on the correct placement of keywords.

<img width="950" alt="description" src="https://cloud.githubusercontent.com/assets/9379524/12143248/c07a2016-b4ca-11e5-8b4d-d480b8cd2c82.png">

**Comment by pwalsh** [comment]
Description I will move up. Keywords: less sure about. I'll leave them where they are for the time being.

**Comment by pwalsh** [comment]
Fixed description in https://github.com/dataprotocols/schemas/commit/f745a06a6ec1f888051af1d9b5f9c3ba336d6f37 https://github.com/dataprotocols/schemas/commit/0fb91cca480a66143552d3818d53566240478a2c https://github.com/dataprotocols/schemas/commit/c206f6eda6e623f4ec15a94a1b477c5f28b5298e

WONTFIX for keywords at this stage.
