### ISSUE TITLE
Make Type and Format in Fields choose from valid options

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/datapackagist#198]
The field type and format are [defined in the spec](http://dataprotocols.org/json-table-schema/#field-types-and-formats). Consider adding a drop down box of valid values in the user interface instead of/as well as allowing free text input.

**Comment by pwalsh** [comment]
@Stephen-Gates agreed this would be a vital, and simple, UX win.

**Comment by borysyuk** [comment]
Done. I have change `type` field only, because `format` has only one value `default`.

**Comment by pwalsh** [comment]
DONE.
