### ISSUE TITLE
The "datapackage from remote functionality broke again"

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#201]
Example: http://datapackagist.okfnlabs.org/base/from/?url=https%3A%2F%2Frawgit.com%2Frichhall%2Fa3e534c7f63911c22082%2Fraw%2Fc758f90a07804ffe23ca2f97b8fe696f71106d7f%2Fopendata_cambridgeshireinsight_org_uk_CORS.json

Which is trying to read from this: https://rawgit.com/richhall/a3e534c7f63911c22082/raw/c758f90a07804ffe23ca2f97b8fe696f71106d7f/opendata_cambridgeshireinsight_org_uk_CORS.json - an example DKAN API endpoint.

**Comment by borysyuk** [comment]
@pwalsh I opened examle and `datapackagist` little freeze but showed JSON file. I didn't see any errors in javascript console.

**Comment by pwalsh** [comment]
@borysyuk confirmed. Works for me.

**Comment by pwalsh** [comment]
@borysyuk the population is working, but the logic has broken. For example, see:

(  cc @Stephen-Gates ) http://datapackagist.okfnlabs.org/base/from/?url=http%3A%2F%2Fdata.qld.gov.au%2Fapi%2Faction%2Fpackage_show%3Fid%3Ddays-lost-for-tmr-employee-injuries

Which populates the data but actually creates an invalid data package (`resources[0].name`, `resources[0].hash`)

# Tasks

* [ ] Update mapper for import

**Comment by borysyuk** [comment]
done.
