### ISSUE TITLE
Unable to select licence object after name entered

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/datapackagist#204]
When the edit data package first appears you can choose if a licence is a object (i.e. name and url) or a string (name only e.g. CC BY).
<img width="657" alt="screenshot 2016-01-10 21 37 02" src="https://cloud.githubusercontent.com/assets/9379524/12221332/58e7c014-b7e2-11e5-9a6a-198a8945da97.png">

As soon as you type in a data package name, this option disappears
<img width="1120" alt="screenshot 2016-01-10 21 30 07" src="https://cloud.githubusercontent.com/assets/9379524/12221337/86a964a8-b7e2-11e5-8e53-d898ef12caf5.png">

Further, if you select a licence object, you can't revert to a licence name if you change your mind.

**Comment by pwalsh** [comment]
thanks.

**Comment by pwalsh** [comment]
FIXED.
