### ISSUE TITLE
Licence type ignores text after first space

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/datapackagist#205]
Note "CC BY" in user interface and just "CC" in data package

<img width="1126" alt="screenshot 2016-01-10 21 44 29" src="https://cloud.githubusercontent.com/assets/9379524/12221359/6b1df040-b7e3-11e5-9c46-165d448bc33d.png">

**Comment by pwalsh** [comment]
Thanks.

**Comment by borysyuk** [comment]
i have tested on Chrome and Firefox and I cann't reproduse bug.

**Comment by Stephen-Gates** [comment]
1. Select Tabular Data Package profile
2. Go to Licence and select Object
3. Enter Licence Type with a space
4. Enter URL

<img width="1123" alt="screenshot 2016-01-16 05 49 50" src="https://cloud.githubusercontent.com/assets/9379524/12363560/1ea6f802-bc15-11e5-8fb2-310df4a1e653.png">

The behaviour is not consistent. I'm using Safari. Cannot recreate in Chrome.

**Comment by pwalsh** [comment]
@borysyuk please check on Safari.

**Comment by borysyuk** [comment]
@pwalsh The problem was in `autocomplete` of `INPUT` elements into Safari. `JSON Editor` doesn't generate `change` event on autocomplete. Autocomplete has been disabled

**Comment by pwalsh** [comment]
@borysyuk great. Please deploy the fix and we can close this issue.

**Comment by pwalsh** [comment]
FIXED.
