### ISSUE TITLE
Infer ISO 8601 Date Time formats?

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/datapackagist#206]
Does datapackagist detect [ISO 8601 date time formats](https://en.wikipedia.org/wiki/ISO_8601)? e.g. 2013-12-25T11:59:00

I uploaded this resource https://data.qld.gov.au/dataset/4053191c-b661-4cf2-a632-079ee35335e4/resource/faaa6d6c-1895-4090-821e-31ef5ed1678e/download/qgictdbtmruploadoct2015.CSV and Dates were suggested to be integers

<img width="892" alt="screenshot 2016-01-10 21 58 50" src="https://cloud.githubusercontent.com/assets/9379524/12221404/60c5ca62-b7e5-11e5-8ccd-1ae9bca1c1c9.png">

**Comment by pwalsh** [comment]
@Stephen-Gates yes it does, I can see our inference of data types is broken.

**Comment by pwalsh** [comment]
@borysyuk the infer method of `jsontableschema-js` must have some issues. We've been using it elsewhere, in particular @kravets-levko uses it in https://github.com/openspending/os-packager with success. We need to see what the specific issue is here, and check if we have an implementation problem here, or if we need to refactor and expand ties suite over at https://github.com/okfn/jsontableschema-js

**Comment by pwalsh** [comment]
This will also be related to https://github.com/okfn/datapackagist/issues/169

**Comment by borysyuk** [comment]
@pwalsh nor `jsontableschema` supports date and datetime in ISO 8601 by default.
But date is in other format than  ISO 8601  in example csv

**Comment by pwalsh** [comment]
@borysyuk yes I see. Once you deploy the new changes we can resolve this with #169

**Comment by Stephen-Gates** [comment]
Sorry, my mistake. I will test with other datasets and report back.

**Comment by pwalsh** [comment]
@Stephen-Gates just wait until @borysyuk deploys new code tomorrow first, as he has fixed a crucial code path for guessing data types.

**Comment by Stephen-Gates** [comment]
@pwalsh will do.

**Comment by pwalsh** [comment]
CLOSED.
