### ISSUE TITLE
Help text for resource name and title incorrect

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/datapackagist#207]
The Help text for resource name and title incorrect uses the word "package" instead of "resource".

Try: 
 - An identifier for this ~~package~~ resource. Lower case characters with '.', '_' and '-' are allowed
 - A human-readable title for this ~~package~~ resource

<img width="831" alt="screenshot 2016-01-10 22 19 22" src="https://cloud.githubusercontent.com/assets/9379524/12221492/d3e2777c-b7e8-11e5-98f1-935baf6a8d3f.png">
.

**Comment by Stephen-Gates** [comment]
Same issue with resource description.

**Comment by pwalsh** [comment]
Fixed in https://github.com/dataprotocols/schemas/commit/7ea023b68279028191096dc321d2dbc4bf0e85a7
