### ISSUE TITLE
Publish datapackage-outfile on NPM

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#43]
So that it can be used by others

**Comment by gvidon** [comment]
@pwalsh should we create new repo for ```datapackage-outfile```?

**Comment by pwalsh** [comment]
yes: https://github.com/okfn/datapackage-outfile-js

**Comment by alexeyk** [comment]
Files added to the repository.

**Comment by pwalsh** [comment]
Published: https://www.npmjs.com/package/datapackage-outfile
