### ISSUE TITLE
Integration with CKAN/DKAN

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#44]
First take on the way we'll implement:

* On some CKAN/DKAN instance, there is a button on a dataset page to "Create a Data Package"
* That makes a GET request to a Data Packagist instance, with some param like: `?source=ckan&api_version=3&identifier={the_dataset_id}`
* When datapackagist gets these params, it know it needs to build a datapackage **from** the source (`datapackage-from-remote` ?)
* based on the source & version, `datapackage-from-remote` uses the `identifier` to query the remote endpoint, and correctly get the data it needs from the response object
  * so, `datapackage-from-remote` has some built in config for different remotes by default - eg: ckan api to start with, which dkan also supports
  * user could write a custom remote in code
* From here, all the normal Data Packagist stuff happens

So, we are implementing a generic API to build a datapackage from some remote API endpoint, where that endpoint is expected to have certain properties that give us the metadata we need, and of course the references to the files the package describes. We implement this through some "Remote" backend config interface that does those simple mappings we need, and we ship with a CKAN/DKAN remote, supporting V2 and V3 apis (if they are different in any way).

## Tasks

* [x] Put all code in https://github.com/okfn/datapackage-from-remote-js so we can publish to npm

**Comment by pwalsh** [comment]
And here is an example.

* This is a dataset page on a CKAN instance: http://datahub.io/dataset/population-number-by-governorate-age-group-and-gender-2010-2014
* This is the API endpoint for the package: http://datahub.io/api/action/package_show?id=population-number-by-governorate-age-group-and-gender-2010-2014
  * it also can be accessed via uuid: http://datahub.io/api/action/package_show?id=028191c1-84a6-4ac0-ba03-3f51d635a092
  * and via specific API version: http://datahub.io/api/3/action/package_show?id=028191c1-84a6-4ac0-ba03-3f51d635a092

So, there would be a button somewhere that does this GET request:

http://datapackgist.okfnlabs.org/?source=ckan&version=3&identifier=028191c1-84a6-4ac0-ba03-3f51d635a092

and when Data Packagist gets source, version and identifier params, it will trigger the `datapackage-from-remote` logic

**Comment by gvidon** [comment]
@pwalsh probably passing datastore URL and format instead of identifier will make API more extendable? This way API request should look like this ```?source=ckan&api_version=3&url=http://this.is/dataset.json&format=json```.

**Comment by pwalsh** [comment]
@gvidon yes, good idea. go for it.

**Comment by pwalsh** [comment]
@gvidon what do you think about the suggestion of doing it as a json object:

http://datapackgist.okfnlabs.org/?from-remote={"source":"ckan","version":3,"identifier":"028191c1-84a6-4ac0-ba03-3f51d635a092"}

then, we just have one param we listen for: `from-remote`? I don't mind either way - you can decide.

**Comment by gvidon** [comment]
@pwalsh what is the benefit of a single request param?

**Comment by pwalsh** [comment]
@gvidon truth is: no obvious benefit, apart from the logical grouping.

**Comment by gvidon** [comment]
@pwalsh so, you mean that API end point may have other json-groupped params?

**Comment by pwalsh** [comment]
@gvidon no, I don't know :). Let's just leave it for now, and do it however you prefer.

**Comment by gvidon** [comment]
@pwalsh do we use basic schema (profile) to create ```datapackage.json``` from any remote end point? Or do we need to pass schema param to datapackgist API?

**Comment by pwalsh** [comment]
@gvidon very good point - I didn't even think of that until now.

yes, we will need the called to pass another param: `datapackage={ID}` where {ID} is the id from the registry: https://github.com/dataprotocols/registry/blob/master/registry.csv

s that also means that datapackage-from-remote depends on datapackage-registry

**Comment by pwalsh** [comment]
https://www.npmjs.com/package/datapackage-from-remote
