### ISSUE TITLE
UI/UX for form data entry

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#46]
Form UX: See all comments in this: https://www.marqueed.com/collections/186126

Most of the things are logic that repeats, so read all comments - there are probably ways to do some of this with the json-editor API.

**Comment by gvidon** [comment]
@pwalsh could you please provide more details on this task?

**Comment by pwalsh** [comment]
Notes to self....

* nesting of resource objects, and remove some of the selector options

**Comment by gvidon** [comment]
@pwalsh could you please send invitation again?

**Comment by pwalsh** [comment]
@gvidon

**Comment by alexeyk** [comment]
* [ ] Remove collapse, edit json, and object properties (#1, #8, #9 screen1; #1 + screen 2);
* [ ] Replace "Expand" with a "+" symbol, have the button be a square, have the button right-aligned. Use the "+" symbol from font-awesome

**Comment by gvidon** [comment]
https://www.marqueed.com/collections/186126/images/837253/
- [ ] 7

https://www.marqueed.com/collections/186126/images/837249/
- [ ] 9
