### ISSUE TITLE
Example in README is broken

### ISSUE THREAD

**Issue by davidread** [okfn/datapackagist#62]
The example link in the README is: <http://datapackagist.okfnlabs.org/?url=http%3A%2F%2Fdatahub.io%2Fapi%2Faction%2Fpackage_show%3Fid%3Dpopulation-number-by-governorate-age-group-and-gender-2010-2014> which shows me just empty fields for the Data Package - seems broken.

**Comment by pwalsh** [comment]
Correct. It is still WIP. Will be ready this week.

**Comment by davidread** [comment]
Ah, cool

**Comment by pwalsh** [comment]
I'll leave this open so I can ping you when this part works.

**Comment by pwalsh** [comment]
@davidread should be working now.
