### ISSUE TITLE
Empty div appears under download button

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#72]
![unwanted-div](https://cloud.githubusercontent.com/assets/791678/8486807/3b63bd90-2110-11e5-8d5c-6d0ac81c97f6.png)

**Comment by gvidon** [comment]
@alexeyk was not able to reproduce it locally.

**Comment by alexeyk** [comment]
Unable to reproduce https://www.dropbox.com/s/3uhfcmahpoohes0/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-03%2018.38.54.png?dl=0
Tested lastest Chrome, Safari, Firefox.

**Comment by gvidon** [comment]
@pwalsh need to know more on how to reproduce it.

**Comment by pwalsh** [comment]
Talked now with @gvidon 

1. remove this error list, as errors are inline on form anyway
2. For me, on all browsers this issue is caused by .error-list having "overflow: scroll" - the thing I see is the divider for the scroll bar.
