### ISSUE TITLE
When opening data dependencies, the first object is not visible

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#73]
![data_dependencies_missing_add_item](https://cloud.githubusercontent.com/assets/791678/8486822/5a7a83c6-2110-11e5-897b-fa1da796a883.png)

Should be same behaviour as Resources, for example.

**Comment by gvidon** [comment]
@alexeyk need to update this https://github.com/okfn/datapackagist/blob/master/datapackagist/src/scripts/components/ui/descriptoredit.js#L269

**Comment by alexeyk** [comment]
@gvidon "Data Dependencies" field have type = 'object'. form don't know how to render it. There are no other such types in schema object. 
https://www.dropbox.com/s/njfppfnagx0h319/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-04%2020.36.40.png?dl=0

**Comment by gvidon** [comment]
@pwalsh ```.dataDependencies``` is not described well in schema https://rawgit.com/dataprotocols/schemas/master/data-package.json ```json-editor``` just know nothing about how to represent it.

We need to implement exceptional processing for such cases or update schema to be more precise.

**Comment by pwalsh** [comment]
Yes, I see. Let's ignore for now then
