### ISSUE TITLE
Resource.schema does not show

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#74]
![cant_add_schema](https://cloud.githubusercontent.com/assets/791678/8486840/7faadf1a-2110-11e5-91ca-025aa16841ad.png)

**Comment by gvidon** [comment]
@alexeyk need to update this https://github.com/okfn/datapackagist/blob/master/datapackagist/src/scripts/components/ui/descriptoredit.js#L269

**Comment by alexeyk** [comment]
@gvidon it's looking like same issue as per #73 
https://www.dropbox.com/s/bw419xt17hvcqua/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-04%2020.40.27.png?dl=0
Type of schema is object without fields specification.

**Comment by pwalsh** [comment]
@gvidon @alexeyk ok I see. There is nothing to be done about this then, until the user adds a resource file.
