### ISSUE TITLE
Resource item 1 stays empty when new resource added

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#77]
![resource_item_1](https://cloud.githubusercontent.com/assets/791678/8487042/f192b6d8-2111-11e5-9ee4-52fb1837e1a6.png)

**Comment by gvidon** [comment]
@pwalsh what should happen to item 1 when new item added?

**Comment by pwalsh** [comment]
Should be populated with the data

**Comment by gvidon** [comment]
@pwalsh sorry, can't get the idea.

* user expands Resources
* there is one empty item, but he clicks Add item
* new empty item added.

Which data should first item be populated with?

**Comment by pwalsh** [comment]
If user does "upload data file" action from top of resources section, and item 1 is empty, the uploaded data file should populate item 1

**Comment by gvidon** [comment]
@alexeyk remove empty value from Resources when uploading data file. Should be done in ```DataUploadView```.
