### ISSUE TITLE
Use # for routes

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#87]
When we develop locally, we do not need a hash for routing, as we are running from a node server.

When we deploy, the app runs as a pure client side app, so routes do not work.

**Comment by gvidon** [comment]
@pwalsh I'm sure that we always need to find the way to have clean pathes. ```#``` makes it very ugly and unreadable.

Can change to ```#``` if it is absolute must have.

**Comment by pwalsh** [comment]
@gvidon must change, yes. we are running live off a static server so there is no other option now.

**Comment by gvidon** [comment]
@pwalsh I can configure static web server to have clean pathes:) nginx has simple config for this.

**Comment by pwalsh** [comment]
Of course. but we are serving from GitHub pages which is free and easy.
