### ISSUE TITLE
Create new object derived from JSONEditor and extend it with all the customization of DescriptorEditView.reset()

### ISSUE THREAD

**Issue by gvidon** [okfn/datapackagist#89]
```.reset()``` is becoming too large.

* Create view in another ```.js```
* derive it from ```JSONEditor```
* move there all the customization and handlers of ```this.layout.form.on('ready', (function() {...}).bind(this))```from ```DescriptorEditView.reset()```.

**Comment by pwalsh** [comment]
@gvidon is this still relevant?

**Comment by gvidon** [comment]
Yes
