### ISSUE TITLE
Create an object that will wrap json-editor Editor object and expose some extra methods for Resource row

### ISSUE THREAD

**Issue by gvidon** [okfn/datapackagist#96]
The main purpose of this task is to decouple https://github.com/okfn/datapackagist/blob/master/datapackagist/src/scripts/components/ui/descriptoredit.js and possibly other related .js to move all routines which work with Resource editor into ```ui/resource-editor.js```

- [x] What method we need currently for sure is getting resource data which may be presented as ```.dataSource``` attribute (added during user upload in datapackagist UI) or as URL, should return promise (possbily) — ```ResourceEditor.getDataSource() => {data: <CSV plain text>, schema: <object>}```
- [x] after ```ResourceEditor.getDataSource()``` is ready this routine https://github.com/okfn/datapackagist/commit/f34c65a2f3b3af6e975bb66cf80cc0babb6d09fd#diff-81d6b1679a4a30214363ddb494cb33e3R134 should be rewritten.

**Comment by pwalsh** [comment]
@gvidon is this still relevant?

**Comment by gvidon** [comment]
Yes

**Comment by alexeyk** [comment]
I created custom editor for resources (inherit from array type).
Setup it for resources field.
Extended in with ```add``` method with code from ```descriptoredit.js```.

**Comment by alexeyk** [comment]
Working on the getDataSource. Estimate completion time about 1 hour.

**Comment by alexeyk** [comment]
Added ```dataSources``` param to constructor of json editor form.
Extended constructor of resources editor to restore data sources based on added new param.
Moved out resources data source code from ```descriptioredit.js```

**Comment by pwalsh** [comment]
@alexeyk @gvidon is this waiting for checking my @gvidon ?

**Comment by gvidon** [comment]
@pwalsh yes, will take a look now.

**Comment by gvidon** [comment]
@alexeyk 
- [ ] ```.getDataSource()``` should be the method of Resource editor, not of Resources array editor. It should return a data for a single row
- [ ] you forgot that reource data may be presented as URL

**Comment by gvidon** [comment]
@alexeyk also note, that ```.getDataSource()``` should always return ```Promise``` object.
* in case resource row has URL property and ```.dataSource``` is undefined, it should fetch resource from the URL (if **only** it is CSV, ignore other media types and reject), infer schema, populate ```.dataSource``` and resolve into it
* in case there is ```.dataSource```, ```Promise``` should immediately resolve into ```.dataSource```.

After this algorithm is implemented in editor's method ```.getDataSource()``` you will be able to
- [ ] replace most part of this routine https://github.com/okfn/datapackagist/blob/master/datapackagist/src/scripts/components/ui/validationresult.js#L77-L100

**Comment by alexeyk** [comment]
@gvidon we have not array or editor ```Resource```. We have ```root.resources``` with type array. It's one editor what have array of simple types (string, object, integer etc) https://goo.gl/moa0zd . There are no dedicated editor for one resource.

**Comment by alexeyk** [comment]
@gvidon for meet your requirements i creating ```.getDataSource(rowIndex)``` what is return promise with resource data for specified row index.

**Comment by gvidon** [comment]
@alexeyk ok, I see. If the Resources editor row item is a generic object of the ```json-editor```, there is no other way.

**Comment by alexeyk** [comment]
Work with CSV data from URL for getDataSource will be done tomorrow at middle time.

**Comment by alexeyk** [comment]
```replace most part of this routine``` currently in debugging state. Completion of whole issue expecting during weekend.

**Comment by gvidon** [comment]
@alexeyk this is what I meant what talked about replacing routine — https://gist.github.com/gvidon/35bd261e7f625c0e39aa
