### ISSUE TITLE
JSON Object/Validation issues

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#97]
* [x] Changing the data package doesn't seem to have any effect on the validation state of the data (if it was valid against original package, and then changed to a package that data is invalid against, UI still shows as valid)
* [x] Remove "Validate Schema" button from under form - this now happens against the form in "real time" anyway
* [x] In some circumstances, I can still create Data packages which should be valid, but that are apparently not valid according to our validation (ie: as a user, it does not let me download the descriptor). [Example](http://datapackagist.okfnlabs.org/#/base/from/?url=http%3A%2F%2Fdatahub.io%2Fapi%2Faction%2Fpackage_show%3Fid%3Dpopulation-number-by-governorate-age-group-and-gender-2010-2014)
* [x] The output JSON object shows all fields. I'm wondering if this causes validation problems. Remove all empty fields from the created object

**Comment by gvidon** [comment]
- [ ] if no fields filled up then form is empty when switching from Data Package profile to Tabular Datapackage Profile https://www.dropbox.com/s/jyab1txyj66ecvk/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-15%2011.52.15.png?dl=0
- [ ] no errors, Download button still inactive

**Comment by gvidon** [comment]
- [ ] title property of rendered JSON not populated https://www.dropbox.com/s/fvmwev1lrnqmn8l/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-07-16%2013.31.26.png?dl=0
